version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - .m2/repository/init.sql:/docker-entrypoint-initdb.d/1.sql
      - .m2/repository/UserEntitySchema.sql:/docker-entrypoint-initdb.d/2.sql
      - .m2/repository/TypingtestSchema.sql:/docker-entrypoint-initdb.d/3.sql
      - .m2/repository/LeaderboardSchema.sql:/docker-entrypoint-initdb.d/4.sql
      - .m2/repository/enWords.csv:/var/lib/mysql-files/enWords.csv
      - .m2/repository/enQuote.csv:/var/lib/mysql-files/enQuote.csv
      - .m2/repository/zhWords.csv:/var/lib/mysql-files/zhWords.csv
      - .m2/repository/zhQuote.csv:/var/lib/mysql-files/zhQuote.csv
      - db:/var/lib/mysql
    command:
      - '--local_infile=1'
      - '--explicit_defaults_for_timestamp=1'

  auth:
    depends_on:
      - mysqldb
    build: ./auth
    restart: on-failure
    env_file: ./.env
    ports:
      - $AUTH_LOCAL_PORT:$AUTH_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  typingtest:
    depends_on:
      - mysqldb
    build: ./typingtest
    restart: on-failure
    env_file: ./.env
    ports:
      - $TYPINGTEST_LOCAL_PORT:$TYPINGTEST_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  leaderboard:
    depends_on:
      - mysqldb
    build: ./leaderboard
    restart: on-failure
    env_file: ./.env
    ports:
      - $LEADERBOARD_LOCAL_PORT:$LEADERBOARD_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: